// <auto-generated />
using System;
using LaborProtection.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaborProtection.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230510113124_AddDefaultLampAndBulbsData")]
    partial class AddDefaultLampAndBulbsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaborProtection.Database.Entities.BulbEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("LightFlux")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<short>("Power")
                        .HasColumnType("smallint");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<short>("Voltage")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Bulbs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3827),
                            LightFlux = 1060,
                            Name = "ЛБ18",
                            Power = (short)18,
                            Price = 18f,
                            Type = 1,
                            Voltage = (short)57
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3848),
                            LightFlux = 880,
                            Name = "ЛД18",
                            Power = (short)18,
                            Price = 13f,
                            Type = 2,
                            Voltage = (short)57
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3852),
                            LightFlux = 1060,
                            Name = "ЛБ20",
                            Power = (short)20,
                            Price = 20f,
                            Type = 1,
                            Voltage = (short)57
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3855),
                            LightFlux = 1060,
                            Name = "ЛБ20-2",
                            Power = (short)20,
                            Price = 22f,
                            Type = 1,
                            Voltage = (short)65
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3858),
                            LightFlux = 880,
                            Name = "ЛД20-2",
                            Power = (short)20,
                            Price = 12f,
                            Type = 2,
                            Voltage = (short)65
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3861),
                            LightFlux = 2020,
                            Name = "ЛБ30",
                            Power = (short)30,
                            Price = 26f,
                            Type = 1,
                            Voltage = (short)106
                        },
                        new
                        {
                            Id = 7L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3864),
                            LightFlux = 1980,
                            Name = "ЛБУ30",
                            Power = (short)30,
                            Price = 25f,
                            Type = 3,
                            Voltage = (short)104
                        },
                        new
                        {
                            Id = 8L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3867),
                            LightFlux = 2800,
                            Name = "ЛБ36",
                            Power = (short)36,
                            Price = 28f,
                            Type = 1,
                            Voltage = (short)103
                        },
                        new
                        {
                            Id = 9L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3869),
                            LightFlux = 2800,
                            Name = "ЛБ40",
                            Power = (short)40,
                            Price = 42f,
                            Type = 1,
                            Voltage = (short)103
                        },
                        new
                        {
                            Id = 10L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3872),
                            LightFlux = 3000,
                            Name = "ЛБ40-2",
                            Power = (short)40,
                            Price = 40f,
                            Type = 1,
                            Voltage = (short)110
                        },
                        new
                        {
                            Id = 11L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3875),
                            LightFlux = 2300,
                            Name = "ЛД40-2",
                            Power = (short)40,
                            Price = 40f,
                            Type = 2,
                            Voltage = (short)110
                        },
                        new
                        {
                            Id = 12L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3877),
                            LightFlux = 4600,
                            Name = "ЛБ65",
                            Power = (short)65,
                            Price = 45f,
                            Type = 1,
                            Voltage = (short)110
                        },
                        new
                        {
                            Id = 13L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3880),
                            LightFlux = 5200,
                            Name = "ЛБ80",
                            Power = (short)80,
                            Price = 45f,
                            Type = 1,
                            Voltage = (short)99
                        },
                        new
                        {
                            Id = 14L,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(3883),
                            LightFlux = 4250,
                            Name = "ЛД80",
                            Power = (short)80,
                            Price = 42f,
                            Type = 2,
                            Voltage = (short)105
                        });
                });

            modelBuilder.Entity("LaborProtection.Database.Entities.LampEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BulbCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lamps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BulbCount = 4,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2616),
                            Height = 300f,
                            ImagePath = "Images//Image/EGLO 31756.png",
                            Name = "EGLO 31756",
                            Price = 1928f,
                            Type = 3
                        },
                        new
                        {
                            Id = 2L,
                            BulbCount = 2,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2681),
                            Height = 650f,
                            ImagePath = "Images//Image/Laguna Lightning.png",
                            Name = "Laguna Lightning",
                            Price = 1800f,
                            Type = 4
                        },
                        new
                        {
                            Id = 3L,
                            BulbCount = 4,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2688),
                            Height = 350f,
                            ImagePath = "Images//Image/BS-24.png",
                            Name = "BS-24",
                            Price = 479f,
                            Type = 3
                        },
                        new
                        {
                            Id = 4L,
                            BulbCount = 3,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2693),
                            Height = 700f,
                            ImagePath = "Images//Image/Sign 48.png",
                            Name = "Sign 48",
                            Price = 1169f,
                            Type = 4
                        },
                        new
                        {
                            Id = 5L,
                            BulbCount = 3,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2698),
                            Height = 150f,
                            ImagePath = "Images//Image/EuroLight.png",
                            Name = "EuroLight",
                            Price = 653f,
                            Type = 2
                        },
                        new
                        {
                            Id = 6L,
                            BulbCount = 2,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2702),
                            Height = 200f,
                            ImagePath = "Images//Image/Brille BS-02.png",
                            Name = "Brille BS-02",
                            Price = 419f,
                            Type = 1
                        },
                        new
                        {
                            Id = 7L,
                            BulbCount = 2,
                            CreatedOn = new DateTime(2023, 5, 10, 14, 31, 24, 176, DateTimeKind.Local).AddTicks(2706),
                            Height = 180f,
                            ImagePath = "Images//Image/MAGNUM PLF 30.png",
                            Name = "MAGNUM PLF 30",
                            Price = 267f,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
