// <auto-generated />
using LaborProtection.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaborProtection.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230411132808_ConnectedLampToBulb")]
    partial class ConnectedLampToBulb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaborProtection.Database.Entities.BulbEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("LightFlux")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<short>("Power")
                        .HasColumnType("smallint");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<short>("Voltage")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Bulbs", (string)null);
                });

            modelBuilder.Entity("LaborProtection.Database.Entities.LampBulbEntity", b =>
                {
                    b.Property<long>("LampFK")
                        .HasColumnType("bigint");

                    b.Property<long>("BulbFK")
                        .HasColumnType("bigint");

                    b.HasKey("LampFK", "BulbFK");

                    b.HasIndex("BulbFK");

                    b.ToTable("LambBulb", (string)null);
                });

            modelBuilder.Entity("LaborProtection.Database.Entities.LampEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BulbCount")
                        .HasColumnType("int");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lamps", (string)null);
                });

            modelBuilder.Entity("LaborProtection.Database.Entities.LampBulbEntity", b =>
                {
                    b.HasOne("LaborProtection.Database.Entities.BulbEntity", "Bulb")
                        .WithMany("Lamps")
                        .HasForeignKey("BulbFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaborProtection.Database.Entities.LampEntity", "Lamp")
                        .WithMany("Bulbs")
                        .HasForeignKey("LampFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bulb");

                    b.Navigation("Lamp");
                });

            modelBuilder.Entity("LaborProtection.Database.Entities.BulbEntity", b =>
                {
                    b.Navigation("Lamps");
                });

            modelBuilder.Entity("LaborProtection.Database.Entities.LampEntity", b =>
                {
                    b.Navigation("Bulbs");
                });
#pragma warning restore 612, 618
        }
    }
}
